version: '3.3' 
services:
  redshark.db: 
    image: mysql:8.0 
    command: --default-authentication-plugin=mysql_native_password 
    container_name: redshark.db 
    restart: always 
    environment: 
      MYSQL_ROOT_PASSWORD: 123456 
      MYSQL_USER: "admin" 
      MYSQL_PASSWORD: "goodday"
    volumes:
      - ./mysql_custom_system:/var/lib/mysql
      # new MYSQL_DATABASE will trigger below files be imported by default to the database specified
      #- ./mysql_auto_import_folder:/docker-entrypoint-initdb.d
      - ./mysql_custom_configuration_80:/etc/mysql/conf.d
    ports:
      - 33072:3306 
  redshark.adminer:
    image: adminer 
    container_name: redshark.adminer 
    depends_on:
      - redshark.db 
    restart: always 
    ports: 
      - 17184:8080 
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 123456
      PMA_HOST: redshark.db
  redshark.redis_0:
    image: redis:6.0-custom
    container_name: redshark.redis_0
    restart: always
    volumes: 
      - ./redis/7000/config:/usr/local/etc/redis
      - ./redis/7000/data:/data
  redshark.redis_1:
    image: redis:6.0-custom
    container_name: redshark.redis_1
    volumes:
      - ./redis/7001/config:/usr/local/etc/redis
      - ./redis/7001/data:/data
  redshark.redis_2:
    image: redis:6.0-custom
    container_name: redshark.redis_2
    volumes:
      - ./redis/7002/config:/usr/local/etc/redis
      - ./redis/7002/data:/data

networks: 
  default: 
    external: 
      name: redshark-bridge

